spring.datasource.url=jdbc:postgresql://localhost:5432/news_blog_bd
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

spring.web.resources.static-locations=classpath:/static/

logging.level.com.example.news_blog=DEBUG
spring.thymeleaf.check-template-location=false
jwt.secret=bXlTdXBlclNlY3JldEtleUZvck5ld3NCbG9nMjAyNQ==

server.tomcat.max-http-post-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=50MB
server.tomcat.max-http-form-post-size=50MB

server.tomcat.max-swallow-size=50MB
server.tomcat.connection-timeout=60000